STORAGE_DATASOURCE: mysql
STORAGE_DATASINK: mysql
#MYSQL_INPUT_HOST: 192.168.103.230
#MYSQL_TARGET_HOST: 192.168.103.230
MYSQL_INPUT_USER: dbadmin
MYSQL_INPUT_PASSWORD: au2HFwJ5Q2_rmv
MYSQL_TARGET_USER: dbadmin
MYSQL_TARGET_PASSWORD: au2HFwJ5Q2_rmv
MYSQL_INPUT_DB: original_logs
MUSQL_TARGET_DB: anomalylogsdb
#MODEL_BASE_DIR: "/opt/anomaly_detector/models/"
LOG_SOURCES:
  "logs":
    HOSTNAMES:
      - archives.gov.by-s
      #- bgut.by
      #- bks.gov.by-ssl_lo
      #- brsm.grodno.by-ss
      #- caa.gov.by
      #- dc1-utm1-1
      #- econom.edu.grodno
      #- fk.archives.gov.b
      #- ivje.gov.by
      #- ivje.gov.by-ssl_l
      #- komtsz.gov.by
      #- komtsz.gov.by-ssl
      #- korelichi.gov.by
      #- mggci.by
      #- mstislavl.mogilev
      #- rmcollege.by-ssl_
      #- rspch.by-ssl_log
      #- school13.mogilev
      #- trudgrodno.gov.by
      #- volkovysk.grodno-
      #- zelva.grodno-regi
    MYSQL_TARGET_TABLE: "anomaly_logs"

#PARALLELISM: 8
#LOF_NEIGHBORS: 50
#LOF_NEIGHBORS: 100

MESSAGE_INDEX: message
DATETIME_INDEX: received_at
HOSTNAME_INDEX: hostname
TRAIN_MAX_ENTRIES: 10000
INFER_MAX_ENTRIES: 10000
INFER_TIME_SPAN: 1000000
